<h3>Lgoin</h3>

<form action="" method="post">
	<input type="hidden" name="_method" value="POST"/>
	<input type="email" name="Login[email]" value="admin@email.com" placeholder="Email" maxlength="64" required="required"/><br/>
	<input type="password" name="Login[password]" value="pass" placeholder="Password" pattern="[a-zA-Z0-9]+" required="required"/><br/>
	halfwidth alphabet or digit character<br/>
	<input  type="submit" value="Send"/>
</form>



